# Generated by Django 4.2.19 on 2025-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='device',
        ),
        migrations.AddField(
            model_name='measurement',
            name='frequencia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='nivel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pressao',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
