# Generated by Django 4.2.19 on 2025-02-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_remove_measurement_device_measurement_frequencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='mac_address',
            field=models.CharField(default='00B0D063C226', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='frequencia',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='nivel',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='pressao',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
