# Generated by Django 4.2.19 on 2025-02-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_estado_municipio_remove_fiscalprofile_water_systems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoramento.sistemaabastecimento'),
        ),
    ]
