# Generated by Django 4.2.19 on 2025-03-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0005_measurement_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemaabastecimento',
            name='mac_adress',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
