# Generated by Django 4.2.19 on 2025-03-06 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0006_sistemaabastecimento_mac_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='water_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.sistemaabastecimento'),
        ),
        migrations.DeleteModel(
            name='WaterSystem',
        ),
    ]
